#!/usr/bin/env node
/**
 * v2: platform packages moved to `platform/packages/` and renamed to `@web-app-starter/*`.
 *
 * Why: v2 separates the platform (owned by the starter, replaced wholesale on
 * upgrade) from the app built on it. Everything the platform owns now lives
 * under `platform/`, and its packages carry the `@web-app-starter` scope so an
 * import says who owns the code. `@repo/*` stays the app's own scope:
 * `@repo/backend` and the apps keep their names.
 *
 * What it rewrites, in every text file of an app tree:
 *   1. Import specifiers and package names: `@repo/<platform package>` ->
 *      `@web-app-starter/<platform package>` (imports, CSS `@import`,
 *      package.json dependencies, `transpilePackages`, Turbo task keys, docs).
 *   2. Root-relative and `../`-relative paths to the moved packages:
 *      `packages/<platform package>` -> `platform/packages/<platform package>`
 *      (Tailwind content globs, tsconfig paths, scripts). Paths already under
 *      `platform/` are left alone, which is what makes a second run a no-op.
 *
 * The platform zone (`platform/`) is skipped: it arrives already migrated. Pass
 * `--include-platform` only when migrating the starter itself; inside
 * `platform/` only rule 1 runs, because paths there are relative to the new
 * layout already.
 *
 * Usage (from the repository root, Node 22.6+, no install needed):
 *   ./platform/tooling/node-ts.sh platform/tooling/codemods/v2-platform-packages.ts [--check] [ROOT]
 * Then run `bun install` to relink the workspace.
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { pathToFileURL } from "node:url";

export const PLATFORM_PACKAGES = [
  "app-config",
  "auth",
  "design-patterns",
  "design-system",
  "edge-rate-limit",
  "i18n",
  "ops",
  "paper-roll",
  "starter-sidebar-policy",
] as const;

export const OLD_SCOPE = "@repo";
export const NEW_SCOPE = "@web-app-starter";

const names = PLATFORM_PACKAGES.join("|");
// Matches `<old scope>/<name>`, `<old scope>/<name>/client` and quoted forms; not a longer name
// such as `<old scope>/<name>-ui`, and not app packages such as `@repo/backend`.
const SPECIFIER = new RegExp(`${OLD_SCOPE}/(${names})(?![\\w-])`, "g");
// `packages/<name>/...` at a path start or after a path separator, unless the
// directory before it is `platform/` (already moved) or it is part of a longer
// name such as `my-packages/<name>`.
const PACKAGE_PATH = new RegExp(`(^|[^\\w.@/-]|(?<!platform)/)packages/(${names})(?=[/"'\`\\s)\\]*,;:#]|\\.(?!\\w)|$)`, "gm");

const TEXT_EXTENSIONS = new Set([
  ".ts", ".tsx", ".mts", ".cts", ".js", ".jsx", ".mjs", ".cjs",
  ".json", ".jsonc", ".css", ".scss", ".md", ".mdx", ".yml", ".yaml", ".sh", ".html", ".txt",
]);
const SKIP_DIRECTORIES = new Set([
  ".git", "node_modules", ".next", ".turbo", ".vercel", "out", "dist", "_generated", "coverage",
  "playwright-report", "test-results", "blob-report", ".ci-local-artifacts", ".convex",
]);
// Regenerated by `bun install` after the rewrite.
const SKIP_FILES = new Set(["bun.lock", "bun.lockb", "package-lock.json", "yarn.lock", "pnpm-lock.yaml"]);

export interface RewriteResult { text: string; count: number }

/** Apply the rewrite rules to one file's text. `paths` enables rule 2. */
export function rewriteText(text: string, options: { paths: boolean }): RewriteResult {
  let count = 0;
  let next = text.replace(SPECIFIER, (_match, name: string) => {
    count += 1;
    return `${NEW_SCOPE}/${name}`;
  });
  if (options.paths) {
    next = next.replace(PACKAGE_PATH, (_match, before: string, name: string) => {
      count += 1;
      return `${before}platform/packages/${name}`;
    });
  }
  return { text: next, count };
}

export interface Options { root: string; check: boolean; includePlatform: boolean }
export interface Change { file: string; count: number }

function* textFiles(root: string, relative = ""): Generator<string> {
  for (const entry of fs.readdirSync(path.join(root, relative), { withFileTypes: true })) {
    const name = relative ? `${relative}/${entry.name}` : entry.name;
    if (entry.isDirectory()) {
      if (!SKIP_DIRECTORIES.has(entry.name)) yield* textFiles(root, name);
    } else if (entry.isFile() && !SKIP_FILES.has(entry.name) && TEXT_EXTENSIONS.has(path.extname(entry.name))) {
      yield name;
    }
  }
}

/** Rewrite (or, with `check`, only report) every file under `root`. */
export function migrate(options: Options): Change[] {
  const changes: Change[] = [];
  for (const file of textFiles(options.root)) {
    const inPlatform = file === "platform" || file.startsWith("platform/");
    if (inPlatform && !options.includePlatform) continue;
    const absolute = path.join(options.root, file);
    const before = fs.readFileSync(absolute, "utf8");
    const result = rewriteText(before, { paths: !inPlatform });
    if (result.count === 0 || result.text === before) continue;
    if (!options.check) fs.writeFileSync(absolute, result.text);
    changes.push({ file, count: result.count });
  }
  return changes;
}

const USAGE = `Usage: v2-platform-packages.ts [--check] [--include-platform] [ROOT]
  ROOT                 repository root (default: current directory)
  --check              report what would change, write nothing, exit 1 if anything would
  --include-platform   also rewrite platform/ (starter maintainers only)`;

export function parseArguments(argv: readonly string[]): Options | string {
  let root = ".";
  let check = false;
  let includePlatform = false;
  let rootSeen = false;
  for (const argument of argv) {
    if (argument === "--check") check = true;
    else if (argument === "--include-platform") includePlatform = true;
    else if (argument === "--help" || argument === "-h") return USAGE;
    else if (argument.startsWith("-") || rootSeen) return `unexpected argument: ${argument}\n${USAGE}`;
    else { root = argument; rootSeen = true; }
  }
  return { root: path.resolve(root), check, includePlatform };
}

export function main(argv: readonly string[], out: (line: string) => void = line => process.stdout.write(`${line}\n`)): number {
  const options = parseArguments(argv);
  if (typeof options === "string") {
    out(options);
    return options === USAGE ? 0 : 2;
  }
  if (!fs.existsSync(path.join(options.root, "package.json"))) {
    out(`v2-platform-packages: ${options.root} has no package.json; pass the repository root`);
    return 2;
  }
  const changes = migrate(options);
  const verb = options.check ? "would rewrite" : "rewrote";
  for (const change of changes) out(`${verb} ${change.count} reference(s) in ${change.file}`);
  const total = changes.reduce((sum, change) => sum + change.count, 0);
  out(`v2-platform-packages: ${verb} ${total} reference(s) in ${changes.length} file(s)`);
  if (!options.check && changes.length > 0) out("Next: run `bun install` to relink the workspace.");
  return options.check && changes.length > 0 ? 1 : 0;
}

if (process.argv[1] && pathToFileURL(fs.realpathSync(process.argv[1])).href === import.meta.url) {
  process.exitCode = main(process.argv.slice(2));
}
